[package]
name = "rust_mg5"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_mg5"
#crate-type = ["dylib"]


[dependencies]
colored = "3.0.0"
cxx = "1.0.137"
libc = "0.2.169"
rand = "0.9.0"

[build-dependencies]
cxx-build = "1.0.137"
flate2 = "1.0.35"
tar = "0.4.43"
